checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
filter:
    excluded_paths:
        - "vendor/*"
    paths:
        - "src/*"
tools:
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: true

build:
    dependencies:
        override:
            - "composer install --no-interaction --prefer-dist"
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        coverage:
            environment:
                php:
                    ini:
                        "xdebug.mode": coverage
            tests:
                override:
                    -
                        command: './vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=clover.xml'
                        coverage:
                            file: 'clover.xml'
                            format: 'php-clover'
    environment:
        php:
            version: 8
        mysql: false
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        memcached: false
